# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f1e2fe78ccdccda7a6428bb598cf9dcdddc28343449aba304b46abdbd76fa09e3e9688e08126a6c844f467b15be398710c661a6b42b746faf73ab7f15b3be22

test:
  secret_key_base: dbd76a1c2fda449cce19e82efe8a5557086d9dc6c9fa1f23b51eb886615b56808b0df31847689dcbaec0a7a5ff40c06b469fcd34f382050d92fff5282c2f8349

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
